// Generated by CoffeeScript 1.6.3
(function() {
  var dispatcher;

  dispatcher = function(path, func) {
    var i, l, match, _results;
    dispatcher.path_func = dispatcher.path_func || [];
    if (func) {
      return dispatcher.path_func.push([path, func]);
    }
    i = 0;
    l = dispatcher.path_func.length;
    _results = [];
    while (i < l) {
      func = dispatcher.path_func[i];
      match = path.match(func[0]);
      match && func[1](match);
      _results.push(++i);
    }
    return _results;
  };

  dispatcher(".", function() {
    return $(function() {
      var a, nav_list, _i, _len, _results;
      console.log;
      nav_list = $('ul.nav').find('a');
      _results = [];
      for (_i = 0, _len = nav_list.length; _i < _len; _i++) {
        a = nav_list[_i];
        if (location.pathname === $(a).attr('href')) {
          _results.push($(a).parent('li').addClass('active'));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    });
  });

  dispatcher(location.pathname);

}).call(this);
